project:
  type: website

website:
  description: "A blog built with Quarto"
  site-url: https://silviojr.github.io/silviojr
  title: "silviojr"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/silviojr
      # - icon: bluesky
      #   href: https://bsky.app/silviojr
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css



